-- =============================================================================
--  DIAGNÓSTICO Y REPARACIÓN — Formulario SARLAFT (Persona Jurídica)
--  Base de datos: MineDax
--  Ejecutar en SQL Server Management Studio (SSMS) conectado a MineDax
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
--  PASO 0: Diagnosticar constraint GNC03TERCE (TIP_TERC en GN_TERCE)
--  Ejecutar PRIMERO para saber qué valores acepta TIP_TERC.
-- ─────────────────────────────────────────────────────────────────────────────

-- 0a. Muestra la definición exacta de la constraint
SELECT
    cc.name           AS constraint_name,
    cc.definition     AS constraint_definition
FROM sys.check_constraints cc
JOIN sys.tables            t  ON cc.parent_object_id = t.object_id
JOIN sys.columns           c  ON cc.parent_object_id = c.object_id
                              AND cc.parent_column_id = c.column_id
WHERE t.name = 'GN_TERCE'
  AND c.name = 'TIP_TERC';
GO

-- 0b. Muestra valores de TIP_TERC que ya existen en la tabla
SELECT DISTINCT TIP_TERC, COUNT(*) AS registros
FROM GN_TERCE
WHERE TIP_TERC IS NOT NULL
GROUP BY TIP_TERC;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  PASO 1: Ver columnas actuales de cada tabla
--  (Si una tabla no aparece en el resultado, no existe todavía)
-- ─────────────────────────────────────────────────────────────────────────────
SELECT
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.CHARACTER_MAXIMUM_LENGTH,
    c.IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS c
JOIN INFORMATION_SCHEMA.TABLES t
    ON c.TABLE_NAME = t.TABLE_NAME AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
WHERE t.TABLE_NAME IN (
    'GN_TERCE','GN_JURID','GN_JURID_RL','GN_JURID_CUMP','GN_JURID_PAIS',
    'GN_JURID_JD','GN_JURID_RF','GN_JURID_AC','GN_JURID_FIN',
    'GN_TERCE_BANCO','GN_JURID_PEP','GN_JURID_ACT','GN_JURID_BF',
    'GN_JURID_FIRMA','GN_TERCE_DOC'
)
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;

GO

-- =============================================================================
--  PASO 2: CORRECCIONES — Ejecutar solo las que necesite su esquema
--
--  Cada bloque usa IF NOT EXISTS para ser seguro: no falla si la columna ya
--  existe, y no hace nada si ya está bien. Ejecute todo el bloque de una vez.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_TERCE — Tercero base
--  Columnas requeridas por server.js:
--    TIP_TERC, COD_TPDOC, NUM_IDEN (PK), DIG_VERI, NOM_COMP,
--    COD_PAIS_EXP ← FALTANTE CONFIRMADO (causa el error actual),
--    DIR_TERC, TEL_TERC, TEL_TERC2, DIR_MAIL
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME='GN_TERCE' AND COLUMN_NAME='TEL_TERC2'
)
    ALTER TABLE GN_TERCE ADD TEL_TERC2 CHAR(40) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID — Datos jurídicos principales
--  Columnas reales en la BD (confirmadas por diagnóstico):
--    TIP_VINC varchar(40), MAIL_SARL, COD_CIIU, URL_WEB, TIP_SOCIE,
--    COD_PAIS_ORI, UBIC_SOC, COD_PAIS_SOC, TIP_EMPR, GRUP_EMPR,
--    COD_PAIS_EXP, COD_DEPT_EXP, COD_MPIO_EXP
--  Nota: TIP_VINC recibe el COD_VINC (int) convertido a string desde server.js.
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='TIP_VINC')
    ALTER TABLE GN_JURID ADD TIP_VINC VARCHAR(40) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='MAIL_SARL')
    ALTER TABLE GN_JURID ADD MAIL_SARL VARCHAR(150) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='COD_CIIU')
    ALTER TABLE GN_JURID ADD COD_CIIU VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='URL_WEB')
    ALTER TABLE GN_JURID ADD URL_WEB VARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='TIP_SOCIE')
    ALTER TABLE GN_JURID ADD TIP_SOCIE VARCHAR(60) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='UBIC_SOC')
    ALTER TABLE GN_JURID ADD UBIC_SOC CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='COD_PAIS_SOC')
    ALTER TABLE GN_JURID ADD COD_PAIS_SOC INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='TIP_EMPR')
    ALTER TABLE GN_JURID ADD TIP_EMPR VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='GRUP_EMPR')
    ALTER TABLE GN_JURID ADD GRUP_EMPR CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='COD_PAIS_EXP')
    ALTER TABLE GN_JURID ADD COD_PAIS_EXP INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='COD_DEPT_EXP')
    ALTER TABLE GN_JURID ADD COD_DEPT_EXP INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID' AND COLUMN_NAME='COD_MPIO_EXP')
    ALTER TABLE GN_JURID ADD COD_MPIO_EXP INT NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_RL — Representantes legales
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='TIP_REPR')
    ALTER TABLE GN_JURID_RL ADD TIP_REPR CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='NOM_REPR')
    ALTER TABLE GN_JURID_RL ADD NOM_REPR VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='APE_REPR')
    ALTER TABLE GN_JURID_RL ADD APE_REPR VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='FEC_EXPE')
    ALTER TABLE GN_JURID_RL ADD FEC_EXPE DATE NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='COD_PAIS')
    ALTER TABLE GN_JURID_RL ADD COD_PAIS VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='COD_DEPT')
    ALTER TABLE GN_JURID_RL ADD COD_DEPT VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='COD_MPIO')
    ALTER TABLE GN_JURID_RL ADD COD_MPIO VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='DIR_REPR')
    ALTER TABLE GN_JURID_RL ADD DIR_REPR VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='CEL_REPR')
    ALTER TABLE GN_JURID_RL ADD CEL_REPR VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='TEL_REPR')
    ALTER TABLE GN_JURID_RL ADD TEL_REPR VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RL' AND COLUMN_NAME='MAIL_REPR')
    ALTER TABLE GN_JURID_RL ADD MAIL_REPR VARCHAR(100) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_CUMP — Sistema de cumplimiento (cabecera + oficiales en misma tabla)
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='DESC_NORM')
    ALTER TABLE GN_JURID_CUMP ADD DESC_NORM VARCHAR(MAX) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='NORM_LAFT')
    ALTER TABLE GN_JURID_CUMP ADD NORM_LAFT VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='TIE_JUNTA')
    ALTER TABLE GN_JURID_CUMP ADD TIE_JUNTA CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='SIS_PREVE')
    ALTER TABLE GN_JURID_CUMP ADD SIS_PREVE VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='REL_GRUPO')
    ALTER TABLE GN_JURID_CUMP ADD REL_GRUPO VARCHAR(100) NULL;
GO
-- Columnas de oficiales de cumplimiento (segunda fila, misma tabla)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='TIP_REPR')
    ALTER TABLE GN_JURID_CUMP ADD TIP_REPR CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='NOM_RESP')
    ALTER TABLE GN_JURID_CUMP ADD NOM_RESP VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='APE_RESP')
    ALTER TABLE GN_JURID_CUMP ADD APE_RESP VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='RAZ_RESP')
    ALTER TABLE GN_JURID_CUMP ADD RAZ_RESP VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='DIR_RESP')
    ALTER TABLE GN_JURID_CUMP ADD DIR_RESP VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='TEL_RESP')
    ALTER TABLE GN_JURID_CUMP ADD TEL_RESP VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_CUMP' AND COLUMN_NAME='MAIL_RESP')
    ALTER TABLE GN_JURID_CUMP ADD MAIL_RESP VARCHAR(100) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_JD — Junta directiva
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='TIE_JUNTA')
    ALTER TABLE GN_JURID_JD ADD TIE_JUNTA CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='TIP_REPR')
    ALTER TABLE GN_JURID_JD ADD TIP_REPR CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='TIP_MIEM')
    ALTER TABLE GN_JURID_JD ADD TIP_MIEM VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='NOM_MIEM')
    ALTER TABLE GN_JURID_JD ADD NOM_MIEM VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='APE_MIEM')
    ALTER TABLE GN_JURID_JD ADD APE_MIEM VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='RAZ_MIEM')
    ALTER TABLE GN_JURID_JD ADD RAZ_MIEM VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='DIR_MIEM')
    ALTER TABLE GN_JURID_JD ADD DIR_MIEM VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='TEL_MIEM')
    ALTER TABLE GN_JURID_JD ADD TEL_MIEM VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_JD' AND COLUMN_NAME='MAIL_MIEM')
    ALTER TABLE GN_JURID_JD ADD MAIL_MIEM VARCHAR(100) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_RF — Revisores fiscales
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='TIE_REVIS')
    ALTER TABLE GN_JURID_RF ADD TIE_REVIS CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='TIP_REPR')
    ALTER TABLE GN_JURID_RF ADD TIP_REPR CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='NOM_REVI')
    ALTER TABLE GN_JURID_RF ADD NOM_REVI VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='APE_REVI')
    ALTER TABLE GN_JURID_RF ADD APE_REVI VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='RAZ_REVI')
    ALTER TABLE GN_JURID_RF ADD RAZ_REVI VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='CEL_REVI')
    ALTER TABLE GN_JURID_RF ADD CEL_REVI VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='DIR_REVI')
    ALTER TABLE GN_JURID_RF ADD DIR_REVI VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='TEL_REVI')
    ALTER TABLE GN_JURID_RF ADD TEL_REVI VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='MAIL_REVI')
    ALTER TABLE GN_JURID_RF ADD MAIL_REVI VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='REVI_FIRMA')
    ALTER TABLE GN_JURID_RF ADD REVI_FIRMA CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='RAZ_FIRMA')
    ALTER TABLE GN_JURID_RF ADD RAZ_FIRMA VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='TIP_DOCU_FIR')
    ALTER TABLE GN_JURID_RF ADD TIP_DOCU_FIR INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='NUM_DOCU_FIR')
    ALTER TABLE GN_JURID_RF ADD NUM_DOCU_FIR VARCHAR(20) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_RF' AND COLUMN_NAME='OBS_REVI')
    ALTER TABLE GN_JURID_RF ADD OBS_REVI VARCHAR(MAX) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_AC — Composición accionaria
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='NOM_ACCI')
    ALTER TABLE GN_JURID_AC ADD NOM_ACCI VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='APE_ACCI')
    ALTER TABLE GN_JURID_AC ADD APE_ACCI VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='RAZ_ACCI')
    ALTER TABLE GN_JURID_AC ADD RAZ_ACCI VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='CEL_ACCI')
    ALTER TABLE GN_JURID_AC ADD CEL_ACCI VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='TEL_ACCI')
    ALTER TABLE GN_JURID_AC ADD TEL_ACCI VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='MAIL_ACCI')
    ALTER TABLE GN_JURID_AC ADD MAIL_ACCI VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_AC' AND COLUMN_NAME='PCT_PART')
    ALTER TABLE GN_JURID_AC ADD PCT_PART DECIMAL(6,2) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_FIN — Información financiera
--  Nombres reales confirmados por diagnóstico:
--    ACT_TOTAL, ING_MENS, PAS_TOTAL, EGR_MENS, PATRIMONIO, OTR_ING
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIN' AND COLUMN_NAME='ACT_TOTAL')
    ALTER TABLE GN_JURID_FIN ADD ACT_TOTAL DECIMAL(18,2) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIN' AND COLUMN_NAME='ING_MENS')
    ALTER TABLE GN_JURID_FIN ADD ING_MENS DECIMAL(18,2) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIN' AND COLUMN_NAME='PAS_TOTAL')
    ALTER TABLE GN_JURID_FIN ADD PAS_TOTAL DECIMAL(18,2) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIN' AND COLUMN_NAME='EGR_MENS')
    ALTER TABLE GN_JURID_FIN ADD EGR_MENS DECIMAL(18,2) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIN' AND COLUMN_NAME='PATRIMONIO')
    ALTER TABLE GN_JURID_FIN ADD PATRIMONIO DECIMAL(18,2) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIN' AND COLUMN_NAME='OTR_ING')
    ALTER TABLE GN_JURID_FIN ADD OTR_ING DECIMAL(18,2) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_TERCE_BANCO — Información bancaria
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_BANCO' AND COLUMN_NAME='COD_BANCO')
    ALTER TABLE GN_TERCE_BANCO ADD COD_BANCO VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_BANCO' AND COLUMN_NAME='TIP_CUEN')
    ALTER TABLE GN_TERCE_BANCO ADD TIP_CUEN VARCHAR(10) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_BANCO' AND COLUMN_NAME='NUM_CUEN')
    ALTER TABLE GN_TERCE_BANCO ADD NUM_CUEN VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_BANCO' AND COLUMN_NAME='CUEN_EXTR')
    ALTER TABLE GN_TERCE_BANCO ADD CUEN_EXTR CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_BANCO' AND COLUMN_NAME='NOM_ENT_EXT')
    ALTER TABLE GN_TERCE_BANCO ADD NOM_ENT_EXT VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_BANCO' AND COLUMN_NAME='TIP_CUE_EXT')
    ALTER TABLE GN_TERCE_BANCO ADD TIP_CUE_EXT VARCHAR(10) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_PEP — Exposición política
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_PEP' AND COLUMN_NAME='MAN_RPUB')
    ALTER TABLE GN_JURID_PEP ADD MAN_RPUB CHAR(1) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_PEP' AND COLUMN_NAME='CAR_PUBL')
    ALTER TABLE GN_JURID_PEP ADD CAR_PUBL CHAR(1) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_ACT — Actividades con activos virtuales
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='ACT_VA_FIAT')
    ALTER TABLE GN_JURID_ACT ADD ACT_VA_FIAT CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='ACT_VA_VA')
    ALTER TABLE GN_JURID_ACT ADD ACT_VA_VA CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='ACT_TRANS')
    ALTER TABLE GN_JURID_ACT ADD ACT_TRANS CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='ACT_CUSTO')
    ALTER TABLE GN_JURID_ACT ADD ACT_CUSTO CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='ACT_SERV_FIN')
    ALTER TABLE GN_JURID_ACT ADD ACT_SERV_FIN CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='ACT_SERV_VAP')
    ALTER TABLE GN_JURID_ACT ADD ACT_SERV_VAP CHAR(1) NULL DEFAULT 'N';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_ACT' AND COLUMN_NAME='CERT_INFO')
    ALTER TABLE GN_JURID_ACT ADD CERT_INFO CHAR(1) NULL DEFAULT 'N';
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_BF — Beneficiarios finales
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='TIP_BENE')
    ALTER TABLE GN_JURID_BF ADD TIP_BENE CHAR(1) NULL DEFAULT 'P';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='NOM_BENE')
    ALTER TABLE GN_JURID_BF ADD NOM_BENE VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='APE_BENE')
    ALTER TABLE GN_JURID_BF ADD APE_BENE VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='RAZ_BENE')
    ALTER TABLE GN_JURID_BF ADD RAZ_BENE VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='DIR_BENE')
    ALTER TABLE GN_JURID_BF ADD DIR_BENE VARCHAR(255) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='TEL_BENE')
    ALTER TABLE GN_JURID_BF ADD TEL_BENE VARCHAR(30) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_BF' AND COLUMN_NAME='MAIL_BENE')
    ALTER TABLE GN_JURID_BF ADD MAIL_BENE VARCHAR(100) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_JURID_FIRMA — Firma del representante legal
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIRMA' AND COLUMN_NAME='NOM_FIRM')
    ALTER TABLE GN_JURID_FIRMA ADD NOM_FIRM VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIRMA' AND COLUMN_NAME='APE_FIRM')
    ALTER TABLE GN_JURID_FIRMA ADD APE_FIRM VARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIRMA' AND COLUMN_NAME='FEC_FIRMA')
    ALTER TABLE GN_JURID_FIRMA ADD FEC_FIRMA DATE NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_JURID_FIRMA' AND COLUMN_NAME='ARCH_FIRMA')
    ALTER TABLE GN_JURID_FIRMA ADD ARCH_FIRMA VARCHAR(500) NULL;
GO

-- ─────────────────────────────────────────────────────────────────────────────
--  GN_TERCE_DOC — Documentos adjuntos
-- ─────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='RUT')
    ALTER TABLE GN_TERCE_DOC ADD RUT VARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='CERT_BANC')
    ALTER TABLE GN_TERCE_DOC ADD CERT_BANC VARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='CERT_EXIS')
    ALTER TABLE GN_TERCE_DOC ADD CERT_EXIS VARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='DOC_ID_RL')
    ALTER TABLE GN_TERCE_DOC ADD DOC_ID_RL VARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='EST_FIN')
    ALTER TABLE GN_TERCE_DOC ADD EST_FIN VARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='CERT_ACCI')
    ALTER TABLE GN_TERCE_DOC ADD CERT_ACCI VARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='GN_TERCE_DOC' AND COLUMN_NAME='CART_ACEP')
    ALTER TABLE GN_TERCE_DOC ADD CART_ACEP VARCHAR(500) NULL;
GO

-- =============================================================================
--  VERIFICACIÓN FINAL — Confirmar que todas las tablas tienen sus columnas
-- =============================================================================
SELECT
    t.TABLE_NAME,
    COUNT(*) AS total_columnas
FROM INFORMATION_SCHEMA.COLUMNS c
JOIN INFORMATION_SCHEMA.TABLES t
    ON c.TABLE_NAME = t.TABLE_NAME AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
WHERE t.TABLE_NAME IN (
    'GN_TERCE','GN_JURID','GN_JURID_RL','GN_JURID_CUMP','GN_JURID_PAIS',
    'GN_JURID_JD','GN_JURID_RF','GN_JURID_AC','GN_JURID_FIN',
    'GN_TERCE_BANCO','GN_JURID_PEP','GN_JURID_ACT','GN_JURID_BF',
    'GN_JURID_FIRMA','GN_TERCE_DOC'
)
GROUP BY t.TABLE_NAME
ORDER BY t.TABLE_NAME;
