-- ============================================================
-- MineDax → PostgreSQL DDL
-- Generado: 2026-06-22
-- Fuente: SQL Server 2025 Express, MineDax database
-- Servidor origen: CM-ITD-P-05\SQLEXPRESS
-- ============================================================

-- Habilitar extensión UUID (necesaria para gen_random_uuid())
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Crear esquemas secundarios
CREATE SCHEMA IF NOT EXISTS sec;
CREATE SCHEMA IF NOT EXISTS nomina;

-- NOTA: Las tablas del esquema dbo de SQL Server van al esquema
--       public de PostgreSQL (equivalente directo).

-- ============================================================
-- 1. TABLAS MAESTRAS (MAE_*) — cargar primero: son lookup tables
-- ============================================================

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_AFP" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_AFP" BIGINT NOT NULL,
    "COD_TERC" BIGINT NOT NULL,
    "COD_PILA" VARCHAR(10),
    "TIP_AFP" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_afp_cod_empr" ON public."MAE_AFP" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_afp_cod_terc" ON public."MAE_AFP" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_afp_act_esta" ON public."MAE_AFP" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_ARL" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_ARL" INTEGER NOT NULL,
    "COD_TERC" BIGINT NOT NULL,
    "COD_PILA" VARCHAR(10),
    "COD_CLASE" SMALLINT,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_arl_cod_empr" ON public."MAE_ARL" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_arl_cod_terc" ON public."MAE_ARL" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_arl_act_esta" ON public."MAE_ARL" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_BANCO" (
    "COD_BANCO" INTEGER NOT NULL,
    "NOM_BANCO" VARCHAR(100) NOT NULL,
    "COD_NIT" VARCHAR(20),
    "COD_ASOB" VARCHAR(5),
    "IND_INTER" CHAR(1) NOT NULL DEFAULT 'N',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_banco_act_esta" ON public."MAE_BANCO" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_CARGO" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_CARGO" INTEGER NOT NULL,
    "NOM_CARGO" VARCHAR(150) NOT NULL,
    "NOM_NIVEL" VARCHAR(20) NOT NULL DEFAULT 'OPERATIVO',
    "IND_TRSAB" CHAR(1) NOT NULL DEFAULT 'N',
    "COD_RIESG" INTEGER,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_cargo_cod_empr" ON public."MAE_CARGO" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_cargo_act_esta" ON public."MAE_CARGO" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_CCF" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_CCF" BIGINT NOT NULL,
    "COD_TERC" BIGINT NOT NULL,
    "COD_PILA" VARCHAR(10),
    "COD_REGIO" SMALLINT,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_ccf_cod_empr" ON public."MAE_CCF" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_ccf_cod_terc" ON public."MAE_CCF" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_ccf_act_esta" ON public."MAE_CCF" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_CCOST" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_CCOST" INTEGER NOT NULL,
    "NOM_CCOST" VARCHAR(100) NOT NULL,
    "COD_ABREV" VARCHAR(20),
    "COD_AREA" VARCHAR(20),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_ccost_cod_empr" ON public."MAE_CCOST" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_ccost_act_esta" ON public."MAE_CCOST" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_CEST" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_CEST" BIGINT NOT NULL,
    "COD_TERC" BIGINT,
    "NOM_CEST" VARCHAR(120) NOT NULL,
    "COD_NIT" VARCHAR(20) NOT NULL DEFAULT '0',
    "IND_TIPO" CHAR(1) NOT NULL DEFAULT 'P',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_cest_cod_empr" ON public."MAE_CEST" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_cest_cod_terc" ON public."MAE_CEST" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_cest_act_esta" ON public."MAE_CEST" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_CIIU" (
    "COD_CIIU" VARCHAR(10) NOT NULL,
    "NOM_CIIU" VARCHAR(200) NOT NULL,
    "SEC_CIIU" CHAR(1),
    "DIV_CIIU" CHAR(2),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(250)
);
CREATE INDEX IF NOT EXISTS "idx_mae_ciiu_act_esta" ON public."MAE_CIIU" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_DEPT" (
    "COD_DEPT" INTEGER NOT NULL,
    "NOM_DEPT" VARCHAR(60) NOT NULL,
    "COD_PAIS" INTEGER NOT NULL DEFAULT 0,
    "COD_DANE" CHAR(2),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_dept_act_esta" ON public."MAE_DEPT" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_EMPR" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_CIA" SMALLINT NOT NULL,
    "NOM_EMPR" VARCHAR(120) NOT NULL,
    "COD_NIT" VARCHAR(20) NOT NULL,
    "COD_REPLEG" VARCHAR(100),
    "NOM_PAIS" CHAR(3) NOT NULL DEFAULT 'COL',
    "IND_MATRIZ" CHAR(1) NOT NULL DEFAULT 'S',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_CORT" VARCHAR(20),
    "DIR_EMPR" VARCHAR(200),
    "MUN_EMPR" INTEGER,
    "TEL_EMPR" VARCHAR(20),
    "EML_EMPR" VARCHAR(150),
    "COD_CIIU" VARCHAR(10),
    "COD_CIICAM" VARCHAR(10),
    "FEC_CONST" DATE,
    "NUM_EMPMAX" SMALLINT,
    "IND_ACTIVA" CHAR(1) NOT NULL DEFAULT 'S'
);
CREATE INDEX IF NOT EXISTS "idx_mae_empr_cod_empr" ON public."MAE_EMPR" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_empr_act_esta" ON public."MAE_EMPR" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_EPS" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_EPS" BIGINT NOT NULL,
    "COD_TERC" BIGINT NOT NULL,
    "COD_PILA" VARCHAR(10),
    "TIP_REGIM" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_eps_cod_empr" ON public."MAE_EPS" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_eps_cod_terc" ON public."MAE_EPS" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_eps_act_esta" ON public."MAE_EPS" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_ESTA" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_FLUJ" INTEGER NOT NULL,
    "NOM_FLUJ" VARCHAR(60) NOT NULL,
    "DES_FLUJ" VARCHAR(200),
    "ORD_FLUJ" SMALLINT NOT NULL DEFAULT 0,
    "IND_TIPO" CHAR(1) NOT NULL DEFAULT 'I',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_esta_cod_empr" ON public."MAE_ESTA" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_esta_act_esta" ON public."MAE_ESTA" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_ESTCIV" (
    "COD_ESTCIV" INTEGER NOT NULL,
    "NOM_ESTCIV" VARCHAR(40) NOT NULL,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(80)
);
CREATE INDEX IF NOT EXISTS "idx_mae_estciv_act_esta" ON public."MAE_ESTCIV" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_FCE" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_FCE" INTEGER NOT NULL,
    "COD_TERC" BIGINT NOT NULL,
    "COD_PILA" VARCHAR(10),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_fce_cod_empr" ON public."MAE_FCE" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_fce_cod_terc" ON public."MAE_FCE" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_fce_act_esta" ON public."MAE_FCE" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_GRSAN" (
    "COD_GRSAN" INTEGER NOT NULL,
    "NOM_GRSAN" VARCHAR(20) NOT NULL,
    "COD_LETRA" CHAR(2) NOT NULL DEFAULT '--',
    "COD_FCRH" CHAR(1) NOT NULL DEFAULT '+',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_grsan_act_esta" ON public."MAE_GRSAN" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_MONED" (
    "COD_MONE" SMALLINT NOT NULL,
    "NOM_MONE" CHAR(40) NOT NULL,
    "INI_MONE" CHAR(3) NOT NULL,
    "NUM_DECI" SMALLINT NOT NULL,
    "ACT_USUA" CHAR(8) NOT NULL,
    "ACT_HORA" TIMESTAMP NOT NULL,
    "ACT_ESTA" CHAR(1) NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_mae_moned_act_esta" ON public."MAE_MONED" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_MUNI" (
    "COD_MUNI" INTEGER NOT NULL,
    "SER_MUNI" INTEGER NOT NULL,
    "NOM_MUNI" VARCHAR(80) NOT NULL,
    "COD_PAIS" INTEGER NOT NULL DEFAULT 0,
    "COD_DEPT" INTEGER NOT NULL DEFAULT 0,
    "COD_DANE" CHAR(5),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_muni_act_esta" ON public."MAE_MUNI" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_PAIS" (
    "COD_PAIS" INTEGER NOT NULL,
    "NOM_PAIS" VARCHAR(80) NOT NULL,
    "COD_ISO3" CHAR(3),
    "COD_ISO2" CHAR(2),
    "IND_PRINCI" CHAR(1) NOT NULL DEFAULT 'N',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(80)
);
CREATE INDEX IF NOT EXISTS "idx_mae_pais_act_esta" ON public."MAE_PAIS" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_REGLA" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_REGLA" INTEGER NOT NULL,
    "NOM_REGLA" VARCHAR(60) NOT NULL,
    "COD_ABREV" VARCHAR(10),
    "DES_REGLA" VARCHAR(200),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_regla_cod_empr" ON public."MAE_REGLA" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_regla_act_esta" ON public."MAE_REGLA" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_RIESG" (
    "COD_RIESG" INTEGER NOT NULL,
    "NOM_RIESG" VARCHAR(40) NOT NULL,
    "COD_CLASE" CHAR(1),
    "PCT_COTIZ" NUMERIC(6,4) NOT NULL DEFAULT 0.0000,
    "DES_ACTIV" VARCHAR(300),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_riesg_act_esta" ON public."MAE_RIESG" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_SIST_PREV" (
    "COD_SIST" INTEGER NOT NULL,
    "NOM_SIST" VARCHAR(100) NOT NULL,
    "COD_ABREV" VARCHAR(20),
    "DES_SIST" VARCHAR(300),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(150)
);
CREATE INDEX IF NOT EXISTS "idx_mae_sist_prev_act_esta" ON public."MAE_SIST_PREV" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TERC" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" INTEGER NOT NULL,
    "M_COD" BIGINT,
    "M_COALT" VARCHAR(10),
    "M_CED" BIGINT,
    "M_TIPDOC" VARCHAR(5),
    "M_NOMB" VARCHAR(150),
    "M_SEXO" CHAR(1),
    "M_GRSAN" VARCHAR(5),
    "M_FCTRHH" CHAR(1),
    "M_ESTCIV" VARCHAR(20),
    "M_CIUEXP" VARCHAR(60),
    "M_HIJOS" SMALLINT DEFAULT 0,
    "M_FNAC" DATE,
    "M_CIUDAD" VARCHAR(60),
    "M_TEL1" VARCHAR(20),
    "M_TEL2" VARCHAR(20),
    "M_DIR" VARCHAR(200),
    "M_CORR" VARCHAR(150),
    "M_CARGO" VARCHAR(150),
    "M_PCT" NUMERIC(12,6) DEFAULT 0,
    "M_SBASE" NUMERIC(14,2) DEFAULT 0,
    "M_VLRHR" NUMERIC(12,4) DEFAULT 0,
    "M_TPCTA" VARCHAR(50),
    "M_BANCO" VARCHAR(100),
    "M_NUMCTA" VARCHAR(30),
    "M_SUCUR" VARCHAR(60),
    "M_CCOD" VARCHAR(20),
    "M_CNOM" VARCHAR(60),
    "M_CODCIA" VARCHAR(5),
    "M_CTAGST" VARCHAR(50),
    "M_REGIM" VARCHAR(20),
    "M_TRBSAB" VARCHAR(5),
    "M_CLSAL" VARCHAR(20),
    "M_PENSN" VARCHAR(50),
    "M_L1393" VARCHAR(5),
    "M_MQLIQ" VARCHAR(20),
    "M_TPLIQ" VARCHAR(20),
    "M_EXTRJ" VARCHAR(5),
    "M_RESEXT" VARCHAR(5),
    "M_FING" DATE,
    "M_FRET" DATE,
    "M_FFIN" DATE,
    "M_CRET" VARCHAR(60),
    "M_CONT" INTEGER DEFAULT 0,
    "M_TPCONT" VARCHAR(5),
    "M_METODO" SMALLINT DEFAULT 1,
    "M_PRETE" NUMERIC(14,2) DEFAULT 0,
    "M_DED1" NUMERIC(14,2) DEFAULT 0,
    "M_DED2" NUMERIC(14,2) DEFAULT 0,
    "M_DED3" NUMERIC(14,2) DEFAULT 0,
    "M_DECLR" VARCHAR(5),
    "M_PRSAL" NUMERIC(14,2) DEFAULT 0,
    "M_EPS" VARCHAR(100),
    "M_AFP" VARCHAR(100),
    "M_CAJA" VARCHAR(100),
    "M_ARP" VARCHAR(150),
    "M_CEST" VARCHAR(100),
    "M_RIESG" NUMERIC(6,3) DEFAULT 0,
    "M_HRSMES" SMALLINT DEFAULT 220,
    "M_DISVAC" SMALLINT DEFAULT 15,
    "M_CLAS1" VARCHAR(5),
    "M_CL1NOM" VARCHAR(60),
    "M_RAT14" VARCHAR(5),
    "M_FTE" VARCHAR(5),
    "M_FTENOM" VARCHAR(60),
    "M_SAREA" VARCHAR(5),
    "M_SARNOM" VARCHAR(60),
    "M_NIVCG" VARCHAR(5),
    "M_NIVCNOM" VARCHAR(60),
    "M_DRIVR" VARCHAR(5),
    "M_DRVNOM" VARCHAR(60),
    "M_CLAS7" VARCHAR(5),
    "M_CL7NOM" VARCHAR(60),
    "M_PAGDIA" VARCHAR(5),
    "M_RSIND" VARCHAR(60),
    "M_CODPROV" INTEGER,
    "M_TIPO_AFIL" CHAR(1),
    "M_NOM_PROV" VARCHAR(120),
    "M_COD_NIT" VARCHAR(20),
    "M_COD_ORIG" INTEGER,
    "M_COD_REGIM" CHAR(1),
    "M_IND_ACTIVA" CHAR(1),
    "M_IND_SUPERV" CHAR(1),
    "M_IND_TIPO" CHAR(1),
    "M_PCT_COTIZ" NUMERIC(8,4),
    "ACT_USUA" CHAR(8) DEFAULT 'JECP',
    "ACT_HORA" TIMESTAMP DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_terc_cod_empr" ON public."MAE_TERC" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_terc_cod_terc" ON public."MAE_TERC" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_terc_act_esta" ON public."MAE_TERC" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TERC_BACKUP" (
    "COD_EMPR" SMALLINT NOT NULL,
    "COD_TERC" INTEGER NOT NULL,
    "M_COD" BIGINT,
    "M_COALT" VARCHAR(10),
    "M_CED" BIGINT,
    "M_TIPDOC" VARCHAR(5),
    "M_NOMB" VARCHAR(150),
    "M_SEXO" CHAR(1),
    "M_GRSAN" VARCHAR(5),
    "M_FCTRHH" CHAR(1),
    "M_ESTCIV" VARCHAR(20),
    "M_CIUEXP" VARCHAR(60),
    "M_HIJOS" SMALLINT,
    "M_FNAC" DATE,
    "M_CIUDAD" VARCHAR(60),
    "M_TEL1" VARCHAR(20),
    "M_TEL2" VARCHAR(20),
    "M_DIR" VARCHAR(200),
    "M_CORR" VARCHAR(150),
    "M_CARGO" VARCHAR(150),
    "M_PCT" NUMERIC(12,6),
    "M_SBASE" NUMERIC(14,2),
    "M_VLRHR" NUMERIC(12,4),
    "M_TPCTA" VARCHAR(50),
    "M_BANCO" VARCHAR(100),
    "M_NUMCTA" VARCHAR(30),
    "M_SUCUR" VARCHAR(60),
    "M_CCOD" VARCHAR(20),
    "M_CNOM" VARCHAR(60),
    "M_CODCIA" VARCHAR(5),
    "M_CTAGST" VARCHAR(50),
    "M_REGIM" VARCHAR(20),
    "M_TRBSAB" VARCHAR(5),
    "M_CLSAL" VARCHAR(20),
    "M_PENSN" VARCHAR(50),
    "M_L1393" VARCHAR(5),
    "M_MQLIQ" VARCHAR(20),
    "M_TPLIQ" VARCHAR(20),
    "M_EXTRJ" VARCHAR(5),
    "M_RESEXT" VARCHAR(5),
    "M_FING" DATE,
    "M_FRET" DATE,
    "M_FFIN" DATE,
    "M_CRET" VARCHAR(60),
    "M_CONT" INTEGER,
    "M_TPCONT" VARCHAR(5),
    "M_METODO" SMALLINT,
    "M_PRETE" NUMERIC(14,2),
    "M_DED1" NUMERIC(14,2),
    "M_DED2" NUMERIC(14,2),
    "M_DED3" NUMERIC(14,2),
    "M_DECLR" VARCHAR(5),
    "M_PRSAL" NUMERIC(14,2),
    "M_EPS" VARCHAR(100),
    "M_AFP" VARCHAR(100),
    "M_CAJA" VARCHAR(100),
    "M_ARP" VARCHAR(150),
    "M_CEST" VARCHAR(100),
    "M_RIESG" NUMERIC(6,3),
    "M_HRSMES" SMALLINT,
    "M_DISVAC" SMALLINT,
    "M_CLAS1" VARCHAR(5),
    "M_CL1NOM" VARCHAR(60),
    "M_RAT14" VARCHAR(5),
    "M_FTE" VARCHAR(5),
    "M_FTENOM" VARCHAR(60),
    "M_SAREA" VARCHAR(5),
    "M_SARNOM" VARCHAR(60),
    "M_NIVCG" VARCHAR(5),
    "M_NIVCNOM" VARCHAR(60),
    "M_DRIVR" VARCHAR(5),
    "M_DRVNOM" VARCHAR(60),
    "M_CLAS7" VARCHAR(5),
    "M_CL7NOM" VARCHAR(60),
    "M_PAGDIA" VARCHAR(5),
    "M_RSIND" VARCHAR(60),
    "M_CODPROV" INTEGER,
    "M_TIPO_AFIL" CHAR(1),
    "M_NOM_PROV" VARCHAR(120),
    "M_COD_NIT" VARCHAR(20),
    "M_COD_ORIG" INTEGER,
    "M_COD_REGIM" CHAR(1),
    "M_IND_ACTIVA" CHAR(1),
    "M_IND_SUPERV" CHAR(1),
    "M_IND_TIPO" CHAR(1),
    "M_PCT_COTIZ" NUMERIC(8,4),
    "ACT_USUA" CHAR(8),
    "ACT_HORA" TIMESTAMP,
    "ACT_ESTA" CHAR(1)
);
CREATE INDEX IF NOT EXISTS "idx_mae_terc_backup_cod_empr" ON public."MAE_TERC_BACKUP" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_terc_backup_cod_terc" ON public."MAE_TERC_BACKUP" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_mae_terc_backup_act_esta" ON public."MAE_TERC_BACKUP" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TIP_SOCIE" (
    "COD_SOCIE" INTEGER NOT NULL,
    "NOM_SOCIE" VARCHAR(120) NOT NULL,
    "COD_ABREV" VARCHAR(10),
    "UBIC_SOCIE" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(120)
);
CREATE INDEX IF NOT EXISTS "idx_mae_tip_socie_act_esta" ON public."MAE_TIP_SOCIE" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TPCNT" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TPCNT" INTEGER NOT NULL,
    "NOM_TPCNT" VARCHAR(80) NOT NULL,
    "COD_ABREV" VARCHAR(5),
    "IND_FIJO" CHAR(1) NOT NULL DEFAULT 'N',
    "NUM_DIASMX" SMALLINT,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_tpcnt_cod_empr" ON public."MAE_TPCNT" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_tpcnt_act_esta" ON public."MAE_TPCNT" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TPCTA" (
    "COD_TPCTA" INTEGER NOT NULL,
    "NOM_TPCTA" VARCHAR(60) NOT NULL,
    "COD_ABREV" VARCHAR(20),
    "IND_NUMER" CHAR(1) NOT NULL DEFAULT 'S',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(60)
);
CREATE INDEX IF NOT EXISTS "idx_mae_tpcta_act_esta" ON public."MAE_TPCTA" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TPDOC" (
    "COD_TPDOC" INTEGER NOT NULL,
    "NOM_TPDOC" VARCHAR(60) NOT NULL,
    "COD_ABREV" VARCHAR(5),
    "IND_NUMER" CHAR(1) NOT NULL DEFAULT 'S',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(80)
);
CREATE INDEX IF NOT EXISTS "idx_mae_tpdoc_act_esta" ON public."MAE_TPDOC" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_TPLIQ" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TPLIQ" INTEGER NOT NULL,
    "NOM_TPLIQ" VARCHAR(40) NOT NULL,
    "COD_ABREV" VARCHAR(10),
    "NUM_DIASLQ" SMALLINT NOT NULL DEFAULT 0,
    "NUM_PERIAO" SMALLINT NOT NULL DEFAULT 0,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_mae_tpliq_cod_empr" ON public."MAE_TPLIQ" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_mae_tpliq_act_esta" ON public."MAE_TPLIQ" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS public."MAE_VINC" (
    "COD_VINC" INTEGER NOT NULL,
    "NOM_VINC" VARCHAR(80) NOT NULL,
    "COD_ABREV" VARCHAR(10),
    "DES_VINC" VARCHAR(200),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_EN" VARCHAR(120)
);
CREATE INDEX IF NOT EXISTS "idx_mae_vinc_act_esta" ON public."MAE_VINC" ("ACT_ESTA");

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS sec."MAE_ROL" (
    "ROL_USUA" VARCHAR(10) NOT NULL,
    "ROL_DESC" VARCHAR(100) NOT NULL,
    "ROL_NIVEL" SMALLINT NOT NULL DEFAULT 0,
    "IND_ACT" BOOLEAN NOT NULL DEFAULT 1,
    "FEC_CREA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "MOD_USUA" VARCHAR(50) NOT NULL DEFAULT (suser_sname())
);
CREATE INDEX IF NOT EXISTS "idx_mae_rol_ind_act" ON sec."MAE_ROL" ("IND_ACT");

-- ============================================================
-- 2. TABLAS GENERALES (GN_*)
-- ============================================================

CREATE TABLE IF NOT EXISTS public."GN_ADMIN_USR" (
    "ID_ADMIN" UUID NOT NULL DEFAULT (newid()),
    "USR_ADMIN" VARCHAR(50) NOT NULL,
    "NOM_REAL" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(150) NOT NULL,
    "PWD_HASH" CHAR(64),
    "ESTADO" CHAR(1) NOT NULL DEFAULT 'P',
    "TOK_APROB" CHAR(64),
    "TOK_RESET" CHAR(64),
    "TOK_VENC" TIMESTAMP,
    "FEC_CREA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "FEC_APROB" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."GN_BORRADOR" (
    "TOKEN_DRAFT" UUID NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL,
    "TIP_TERC" CHAR(1) NOT NULL,
    "NUM_IDEN_TXT" VARCHAR(20),
    "DATOS_JSON" TEXT NOT NULL,
    "FEC_GUAR" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "FEC_VENC" TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_gn_borrador_cod_empr" ON public."GN_BORRADOR" ("COD_EMPR");

CREATE TABLE IF NOT EXISTS public."GN_FECHA" (
    "Calendar_Date" DATE NOT NULL,
    "Calendar_Date_String" VARCHAR(10) NOT NULL,
    "shortDate_MM_YY" CHAR(10),
    "shortDate_YY_MM_DD" CHAR(10),
    "Calendar_Month" SMALLINT NOT NULL,
    "Calendar_Day" SMALLINT NOT NULL,
    "Calendar_Year" SMALLINT NOT NULL,
    "Calendar_Quarter" SMALLINT NOT NULL,
    "Day_Name" VARCHAR(9) NOT NULL,
    "Day_of_Week" SMALLINT NOT NULL,
    "Day_of_Week_in_Month" SMALLINT NOT NULL,
    "Day_of_Week_in_Year" SMALLINT NOT NULL,
    "Day_of_Week_in_Quarter" SMALLINT NOT NULL,
    "Day_of_Quarter" SMALLINT NOT NULL,
    "Day_of_Year" SMALLINT NOT NULL,
    "Week_of_Month" SMALLINT NOT NULL,
    "Week_of_Quarter" SMALLINT NOT NULL,
    "Week_of_Year" SMALLINT NOT NULL,
    "Month_Name" VARCHAR(9) NOT NULL,
    "First_Date_of_Week" DATE NOT NULL,
    "Last_Date_of_Week" DATE NOT NULL,
    "First_Date_of_Month" DATE NOT NULL,
    "Last_Date_of_Month" DATE NOT NULL,
    "First_Date_of_Quarter" DATE NOT NULL,
    "Last_Date_of_Quarter" DATE NOT NULL,
    "First_Date_of_Year" DATE NOT NULL,
    "Last_Date_of_Year" DATE NOT NULL,
    "Is_Holiday" BOOLEAN NOT NULL,
    "Is_Holiday_Season" BOOLEAN NOT NULL,
    "Holiday_Name" VARCHAR(50),
    "Holiday_Season_Name" VARCHAR(50),
    "Is_Weekday" BOOLEAN NOT NULL,
    "Is_Business_Day" BOOLEAN NOT NULL,
    "Previous_Business_Day" DATE,
    "Next_Business_Day" DATE,
    "Is_Leap_Year" BOOLEAN NOT NULL,
    "Days_in_Month" SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS public."GN_FUNCI" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_FUNCI" INTEGER NOT NULL,
    "COD_TERC" BIGINT NOT NULL,
    "SEX_FUNC" CHAR(1),
    "COD_GRSAN" INTEGER,
    "COD_ESTCIV" INTEGER,
    "CNT_HIJO" INTEGER,
    "FEC_NAC" TIMESTAMP,
    "CIU_EXPED" INTEGER,
    "COD_CARGO" INTEGER,
    "POR_CARGO" NUMERIC(18,0),
    "VAL_HORA" DOUBLE PRECISION,
    "COD_TPCTA" INTEGER,
    "COD_BANCO" INTEGER,
    "NUM_CTA" BIGINT,
    "NOM_SUCUR" CHAR(10),
    "COD_CCOST" INTEGER,
    "CUE_GASTO" INTEGER,
    "JOR_SABAD" CHAR(10),
    "TIP_SALAR" CHAR(10),
    "CUE_PENSIO" CHAR(10),
    "MOD_LIQUID" CHAR(10),
    "TIP_LIQUID" SMALLINT,
    "EMP_FORAN" CHAR(10),
    "DIR_FORAN" CHAR(10),
    "FEC_INGRES" CHAR(10),
    "FEC_RETIRO" CHAR(10),
    "FEC_FINAL" CHAR(10),
    "CAU_RETIRO" CHAR(10),
    "NUM_CONTRA" INTEGER,
    "TIP_CONTRA" CHAR(10),
    "MET_CONTRA" CHAR(10),
    "POR_RETEN" CHAR(10),
    "DED_VIVIEN" CHAR(10),
    "DED_SALUD" CHAR(10),
    "DED_DEPEN" CHAR(10),
    "PRO_SALUD" CHAR(10),
    "COD_EPS" BIGINT,
    "COD_AFP" BIGINT,
    "COD_CAJA" BIGINT,
    "COD_CESAN" BIGINT,
    "GRA_RIESGO" CHAR(10),
    "DIA_VACAC" CHAR(10),
    "NRO_PCAR" SMALLINT,
    "COD_ARBO" SMALLINT,
    "IDE_ARBO" CHAR(2),
    "RMT_NIVE" INTEGER,
    "COD_PAEX" SMALLINT,
    "COD_DPEX" SMALLINT,
    "TIP_NACI" CHAR(1),
    "COD_PNAC" SMALLINT,
    "COD_AUXF" CHAR(20),
    "COD_PANA" SMALLINT,
    "COD_DPNA" SMALLINT,
    "COD_MPNA" SMALLINT,
    "COD_PAVV" SMALLINT,
    "COD_DPVV" SMALLINT,
    "COD_MPVV" SMALLINT,
    "COD_RUTA" SMALLINT,
    "PRI_RUTA" SMALLINT,
    "SPR_RUTA" SMALLINT,
    "CLA_LIMI" CHAR(1),
    "NRO_LIMI" CHAR(11),
    "DIS_MILI" SMALLINT,
    "LIC_FUNC" CHAR(18),
    "CAT_LICE" CHAR(2),
    "VEN_LICE" TIMESTAMP,
    "DIG_VERI" CHAR(1),
    "COD_PADE" SMALLINT,
    "COD_DPDE" SMALLINT,
    "COD_MPDE" SMALLINT,
    "COD_PACA" SMALLINT,
    "COD_DPCA" SMALLINT,
    "COD_MPCA" SMALLINT,
    "NRO_CELU" CHAR(40),
    "FEC_EXPI" TIMESTAMP,
    "COD_PAEL" SMALLINT,
    "COD_DPEL" SMALLINT,
    "COD_MPEL" SMALLINT,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_funci_cod_empr" ON public."GN_FUNCI" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_funci_cod_terc" ON public."GN_FUNCI" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_funci_act_esta" ON public."GN_FUNCI" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_GPROV" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_PROV" INTEGER NOT NULL,
    "TIPO_AFIL" CHAR(1) NOT NULL DEFAULT 'E',
    "NOM_PROV" VARCHAR(120) NOT NULL,
    "COD_NIT" VARCHAR(20) NOT NULL DEFAULT '0',
    "COD_ORIG" INTEGER,
    "COD_REGIM" CHAR(1),
    "IND_ACTIVA" CHAR(1),
    "IND_SUPERV" CHAR(1),
    "IND_TIPO" CHAR(1),
    "PCT_COTIZ" NUMERIC(8,4),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_TIPO" VARCHAR(3) NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_gn_gprov_cod_empr" ON public."GN_GPROV" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_gprov_act_esta" ON public."GN_GPROV" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_GUSUA" (
    "COD_GUSU" SMALLINT NOT NULL,
    "NOM_GUSU" CHAR(40) NOT NULL,
    "ACT_USUA" CHAR(8) NOT NULL,
    "ACT_HORA" TIMESTAMP NOT NULL,
    "ACT_ESTA" CHAR(1) NOT NULL,
    "GRU_DOMI" VARCHAR(100) NOT NULL DEFAULT '.',
    "PRI_DOMI" INTEGER NOT NULL DEFAULT 0,
    "IND_TWEB" CHAR(1)
);
CREATE INDEX IF NOT EXISTS "idx_gn_gusua_act_esta" ON public."GN_GUSUA" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_VINC" VARCHAR(40),
    "MAIL_SARL" VARCHAR(150),
    "COD_CIIU" VARCHAR(10),
    "URL_WEB" VARCHAR(200),
    "TIP_SOCIE" VARCHAR(60),
    "COD_PAIS_ORI" INTEGER,
    "UBIC_SOC" CHAR(1),
    "COD_PAIS_SOC" INTEGER,
    "TIP_EMPR" VARCHAR(10),
    "GRUP_EMPR" CHAR(1),
    "COD_PAIS_EXP" INTEGER,
    "COD_DEPT_EXP" INTEGER,
    "COD_MPIO_EXP" INTEGER,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_VINC" VARCHAR(255),
    "OTR_CIIU" VARCHAR(255),
    "OTR_SOCIE" VARCHAR(255),
    "OTR_PAIS_EXP" VARCHAR(100),
    "OTR_PAIS_SOC" VARCHAR(100),
    "CTRL_DECLA" CHAR(1),
    "CAL_GRUPO" VARCHAR(20),
    "DESC_GRUPO" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_cod_empr" ON public."GN_JURID" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_cod_terc" ON public."GN_JURID" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_act_esta" ON public."GN_JURID" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_AC" (
    "COD_JAC" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "NOM_ACCI" VARCHAR(80),
    "APE_ACCI" VARCHAR(80),
    "RAZ_ACCI" VARCHAR(200),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_ACCI" VARCHAR(120),
    "CEL_ACCI" VARCHAR(30),
    "TEL_ACCI" VARCHAR(30),
    "MAIL_ACCI" VARCHAR(150),
    "PCT_PART" NUMERIC(5,2),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "TIP_PERS" CHAR(1) DEFAULT 'N',
    "OTR_PAIS" VARCHAR(100),
    "OTR_TPDOC" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_ac_cod_empr" ON public."GN_JURID_AC" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_ac_cod_terc" ON public."GN_JURID_AC" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_ac_act_esta" ON public."GN_JURID_AC" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_ACT" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "ACT_VA_FIAT" CHAR(1),
    "ACT_VA_VA" CHAR(1),
    "ACT_TRANS" CHAR(1),
    "ACT_CUSTO" CHAR(1),
    "ACT_SERV_FIN" CHAR(1),
    "ACT_SERV_VAP" CHAR(1),
    "CERT_INFO" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OPER_VA" CHAR(1) DEFAULT 'N'
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_act_cod_empr" ON public."GN_JURID_ACT" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_act_cod_terc" ON public."GN_JURID_ACT" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_act_act_esta" ON public."GN_JURID_ACT" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_BF" (
    "COD_JBF" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_BENE" CHAR(1),
    "NOM_BENE" VARCHAR(80),
    "APE_BENE" VARCHAR(80),
    "RAZ_BENE" VARCHAR(200),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_BENE" VARCHAR(120),
    "TEL_BENE" VARCHAR(30),
    "MAIL_BENE" VARCHAR(150),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_PAIS" VARCHAR(100),
    "OTR_TPDOC" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_bf_cod_empr" ON public."GN_JURID_BF" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_bf_cod_terc" ON public."GN_JURID_BF" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_bf_act_esta" ON public."GN_JURID_BF" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_CUMP" (
    "COD_JCUMP" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "REL_GRUPO" VARCHAR(120),
    "NORM_LAFT" VARCHAR(200),
    "SIS_PREVE" VARCHAR(60),
    "DESC_NORM" VARCHAR(500),
    "TIE_JUNTA" CHAR(1),
    "TIP_SIST" VARCHAR(60),
    "TIP_REPR" CHAR(1),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "NOM_RESP" VARCHAR(80),
    "APE_RESP" VARCHAR(80),
    "RAZ_RESP" VARCHAR(200),
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_RESP" VARCHAR(120),
    "TEL_RESP" VARCHAR(40),
    "MAIL_RESP" VARCHAR(150),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_PREVE" VARCHAR(255),
    "OTR_PAIS" VARCHAR(100),
    "TIE_NORM" CHAR(1),
    "CEL_RESP" VARCHAR(30),
    "OTR_TPDOC" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_cump_cod_empr" ON public."GN_JURID_CUMP" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_cump_cod_terc" ON public."GN_JURID_CUMP" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_cump_act_esta" ON public."GN_JURID_CUMP" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_FIN" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "ACT_TOTAL" NUMERIC(18,2),
    "ING_MENS" NUMERIC(18,2),
    "PAS_TOTAL" NUMERIC(18,2),
    "EGR_MENS" NUMERIC(18,2),
    "PATRIMONIO" NUMERIC(18,2),
    "OTR_ING" NUMERIC(18,2),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_fin_cod_empr" ON public."GN_JURID_FIN" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_fin_cod_terc" ON public."GN_JURID_FIN" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_fin_act_esta" ON public."GN_JURID_FIN" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_FIRMA" (
    "COD_JFIRMA" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "NOM_FIRM" VARCHAR(80),
    "APE_FIRM" VARCHAR(80),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_FIRMA" DATE,
    "ARCH_FIRMA" VARCHAR(500),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_ARCH" VARCHAR(260),
    "EXT_ARCH" VARCHAR(10),
    "TAM_ARCH" BIGINT,
    "HASH_ARCH" VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_firma_cod_empr" ON public."GN_JURID_FIRMA" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_firma_cod_terc" ON public."GN_JURID_FIRMA" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_firma_act_esta" ON public."GN_JURID_FIRMA" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_JD" (
    "COD_JJD" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_REPR" CHAR(1),
    "TIP_MIEM" VARCHAR(100),
    "NOM_MIEM" VARCHAR(80),
    "APE_MIEM" VARCHAR(80),
    "RAZ_MIEM" VARCHAR(200),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_MIEM" VARCHAR(120),
    "TEL_MIEM" VARCHAR(30),
    "MAIL_MIEM" VARCHAR(150),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "CEL_MIEM" VARCHAR(30),
    "OTR_PAIS" VARCHAR(100),
    "OTR_TPDOC" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_jd_cod_empr" ON public."GN_JURID_JD" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_jd_cod_terc" ON public."GN_JURID_JD" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_jd_act_esta" ON public."GN_JURID_JD" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_OC" (
    "COD_JOC" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_REPR" CHAR(1),
    "NOM_OFIC" VARCHAR(80),
    "APE_OFIC" VARCHAR(80),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_OFIC" VARCHAR(120),
    "CEL_OFIC" VARCHAR(30),
    "TEL_OFIC" VARCHAR(30),
    "MAIL_OFIC" VARCHAR(150),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_oc_cod_empr" ON public."GN_JURID_OC" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_oc_cod_terc" ON public."GN_JURID_OC" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_oc_act_esta" ON public."GN_JURID_OC" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_PAIS" (
    "COD_JPAIS" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "COD_PAIS" INTEGER NOT NULL,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_PAIS" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_pais_cod_empr" ON public."GN_JURID_PAIS" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_pais_cod_terc" ON public."GN_JURID_PAIS" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_pais_act_esta" ON public."GN_JURID_PAIS" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_PEP" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "MAN_RPUB" CHAR(1),
    "CAR_PUBL" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_pep_cod_empr" ON public."GN_JURID_PEP" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_pep_cod_terc" ON public."GN_JURID_PEP" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_pep_act_esta" ON public."GN_JURID_PEP" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_RF" (
    "COD_JRF" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_REPR" CHAR(1),
    "TIE_REVIS" CHAR(1),
    "NOM_REVI" VARCHAR(80),
    "APE_REVI" VARCHAR(80),
    "RAZ_REVI" VARCHAR(200),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_REVI" VARCHAR(120),
    "CEL_REVI" VARCHAR(30),
    "TEL_REVI" VARCHAR(30),
    "MAIL_REVI" VARCHAR(150),
    "REVI_FIRMA" CHAR(1),
    "RAZ_FIRMA" VARCHAR(200),
    "TIP_DOCU_FIR" INTEGER,
    "NUM_DOCU_FIR" VARCHAR(20),
    "OBS_REVI" VARCHAR(300),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "TIP_PERS" CHAR(1) DEFAULT 'N',
    "OTR_PAIS" VARCHAR(100),
    "OTR_TPDOC" VARCHAR(100),
    "OTR_TPDOC_FIR" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_rf_cod_empr" ON public."GN_JURID_RF" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_rf_cod_terc" ON public."GN_JURID_RF" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_rf_act_esta" ON public."GN_JURID_RF" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_JURID_RL" (
    "COD_JRL" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_REPR" CHAR(1),
    "NOM_REPR" VARCHAR(80),
    "APE_REPR" VARCHAR(80),
    "TIP_DOCU" INTEGER,
    "NUM_DOCU" VARCHAR(20),
    "FEC_EXPE" DATE,
    "COD_PAIS" INTEGER,
    "COD_DEPT" INTEGER,
    "COD_MPIO" INTEGER,
    "DIR_REPR" VARCHAR(120),
    "CEL_REPR" VARCHAR(30),
    "TEL_REPR" VARCHAR(30),
    "MAIL_REPR" VARCHAR(150),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_PAIS" VARCHAR(100),
    "OTR_TPDOC" VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_rl_cod_empr" ON public."GN_JURID_RL" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_rl_cod_terc" ON public."GN_JURID_RL" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_jurid_rl_act_esta" ON public."GN_JURID_RL" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_LOG_ACCE" (
    "COD_LOGA" UUID NOT NULL DEFAULT (newid()),
    "COD_USUA" BIGINT,
    "COD_TERC" NUMERIC(18,0),
    "NUM_IDEN" BIGINT,
    "TIP_EVEN" VARCHAR(30) NOT NULL,
    "NOM_RECU" VARCHAR(100),
    "EST_EVEN" VARCHAR(20) NOT NULL,
    "DES_EVEN" VARCHAR(500),
    "IP_ORIG" VARCHAR(50),
    "AGE_HTTP" VARCHAR(500),
    "FEC_EVEN" TIMESTAMP NOT NULL DEFAULT (getdate())
);
CREATE INDEX IF NOT EXISTS "idx_gn_log_acce_cod_terc" ON public."GN_LOG_ACCE" ("COD_TERC");

CREATE TABLE IF NOT EXISTS public."GN_NATUR" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_VINC" VARCHAR(40),
    "MAIL_SARL" VARCHAR(150),
    "COD_NACIO" INTEGER,
    "ACT_PRINC" VARCHAR(100),
    "COD_CIIU" VARCHAR(10),
    "FEC_EXPE" DATE,
    "COD_PAIS_EXP" INTEGER,
    "COD_DEPT_EXP" INTEGER,
    "COD_MPIO_EXP" INTEGER,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_PAIS_EXP" VARCHAR(100),
    "OTR_NACIO" VARCHAR(100),
    "OTR_CIIU" VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS "idx_gn_natur_cod_empr" ON public."GN_NATUR" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_cod_terc" ON public."GN_NATUR" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_act_esta" ON public."GN_NATUR" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_NATUR_ACT" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "ACT_VA_FIAT" CHAR(1),
    "ACT_VA_VA" CHAR(1),
    "ACT_TRANS" CHAR(1),
    "ACT_CUSTO" CHAR(1),
    "ACT_SERV_FIN" CHAR(1),
    "ACT_SERV_VAP" CHAR(1),
    "CERT_INFO" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OPER_VA" CHAR(1) DEFAULT 'N'
);
CREATE INDEX IF NOT EXISTS "idx_gn_natur_act_cod_empr" ON public."GN_NATUR_ACT" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_act_cod_terc" ON public."GN_NATUR_ACT" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_act_act_esta" ON public."GN_NATUR_ACT" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_NATUR_FIN" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "ACT_TOTAL" NUMERIC(18,2),
    "ING_MENS" NUMERIC(18,2),
    "PAS_TOTAL" NUMERIC(18,2),
    "EGR_MENS" NUMERIC(18,2),
    "PATRIMONIO" NUMERIC(18,2),
    "OTR_ING" NUMERIC(18,2),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_natur_fin_cod_empr" ON public."GN_NATUR_FIN" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_fin_cod_terc" ON public."GN_NATUR_FIN" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_fin_act_esta" ON public."GN_NATUR_FIN" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_NATUR_PEP" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "MAN_RPUB" CHAR(1),
    "CAR_PUBL" CHAR(1),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_natur_pep_cod_empr" ON public."GN_NATUR_PEP" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_pep_cod_terc" ON public."GN_NATUR_PEP" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_natur_pep_act_esta" ON public."GN_NATUR_PEP" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_PERMI" (
    "COD_PERM" INTEGER NOT NULL,
    "COD_GUSU" SMALLINT NOT NULL,
    "NOM_GUSU" CHAR(40),
    "NOM_MODU" VARCHAR(50) NOT NULL,
    "TIP_ACCI" VARCHAR(20) NOT NULL,
    "NOM_RECU" VARCHAR(100),
    "IND_ACCE" CHAR(1) NOT NULL DEFAULT 'S',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_permi_act_esta" ON public."GN_PERMI" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_PROVE" (
    "COD_EMPR" SMALLINT NOT NULL,
    "COD_TERC" NUMERIC(13,0) NOT NULL,
    "ABR_PROV" CHAR(10) NOT NULL,
    "TIP_PROV" CHAR(1) NOT NULL,
    "AAC_PROV" CHAR(10) NOT NULL,
    "COD_CALI" SMALLINT NOT NULL,
    "INI_CALI" CHAR(2) NOT NULL,
    "REG_CONT" CHAR(1) NOT NULL,
    "REG_CIVA" CHAR(1) NOT NULL,
    "NRO_RESO" CHAR(15) NOT NULL,
    "MAN_RETE" CHAR(1) NOT NULL,
    "RES_RETE" CHAR(15) NOT NULL,
    "ACU_PROV" NUMERIC(28,6) NOT NULL,
    "COD_IICA" SMALLINT NOT NULL,
    "IMP_RENT" CHAR(1) NOT NULL,
    "COD_ARBO" SMALLINT NOT NULL,
    "IDE_ARBO" CHAR(2) NOT NULL,
    "RMT_NIVE" INTEGER NOT NULL,
    "COD_APRO" SMALLINT NOT NULL,
    "INI_APRO" CHAR(2) NOT NULL,
    "COD_CIIU" CHAR(15) NOT NULL,
    "RED_FACT" CHAR(1),
    "TER_REPR" NUMERIC(9,0) NOT NULL,
    "IND_RECH" CHAR(1) NOT NULL,
    "MAN_FELE" CHAR(13) NOT NULL,
    "NIT_TECN" NUMERIC(13,0) NOT NULL,
    "URL_WSDL" CHAR(200) NOT NULL,
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "COD_GPROV" CHAR(10)
);
CREATE INDEX IF NOT EXISTS "idx_gn_prove_cod_empr" ON public."GN_PROVE" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_prove_cod_terc" ON public."GN_PROVE" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_prove_act_esta" ON public."GN_PROVE" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_SESION" (
    "COD_SESI" UUID NOT NULL DEFAULT (newid()),
    "COD_USUA" BIGINT NOT NULL,
    "COD_TERC" NUMERIC(18,0),
    "FEC_INIC" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "FEC_ULAC" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "FEC_CIER" TIMESTAMP,
    "IP_ORIG" VARCHAR(50),
    "AGE_HTTP" VARCHAR(500),
    "DIS_TIPO" VARCHAR(100),
    "EST_SESI" CHAR(1) NOT NULL DEFAULT 'A',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_gn_sesion_cod_terc" ON public."GN_SESION" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_sesion_act_esta" ON public."GN_SESION" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_TERCE" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "NUM_IDEN" BIGINT,
    "DIG_VERI" SMALLINT,
    "COD_ALT" VARCHAR(8),
    "COD_TPDOC" INTEGER,
    "NOM_COMP" VARCHAR(240),
    "NOM_TERC" CHAR(40),
    "SEG_NOMB" VARCHAR(40),
    "APE_TERC" CHAR(40),
    "SEG_APEL" VARCHAR(40),
    "COD_MPIO" SMALLINT,
    "TEL_TERC" CHAR(30),
    "TEL_TERC2" CHAR(40),
    "DIR_TERC" CHAR(120),
    "DIR_TERCC" CHAR(120),
    "DIR_GEOLO" CHAR(200),
    "DIR_MAIL" VARCHAR(150),
    "TIP_TERC" CHAR(1),
    "ACT_INAC" CHAR(1),
    "TER_PROP" CHAR(1),
    "EST_MERC" CHAR(1),
    "REG_CONT" CHAR(1),
    "REG_CIVA" CHAR(1),
    "NRO_RESO" CHAR(15),
    "TER_EMPL" CHAR(1) DEFAULT 0,
    "MAN_RETE" CHAR(1),
    "RES_RETE" CHAR(15),
    "COD_ARBO" SMALLINT,
    "IDE_ARBO" CHAR(2),
    "RMT_NIVE" INTEGER,
    "IDE_EXTE" CHAR(30) DEFAULT '.',
    "MAN_DIGV" CHAR(1) DEFAULT 'N',
    "FEC_GCON" TIMESTAMP,
    "FEC_RETE" TIMESTAMP,
    "ABR_TERC" CHAR(10) DEFAULT '.',
    "MAT_MERC" CHAR(20) DEFAULT '.',
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "MAN_DOCE" CHAR(1) DEFAULT 'N',
    "OTR_TPDOC" VARCHAR(100),
    "COD_EDIT" CHAR(64)
);
CREATE INDEX IF NOT EXISTS "idx_gn_terce_cod_empr" ON public."GN_TERCE" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_terce_cod_terc" ON public."GN_TERCE" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_terce_act_esta" ON public."GN_TERCE" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_TERCE_BANCO" (
    "COD_TBANCO" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "COD_BANCO" INTEGER,
    "TIP_CUEN" INTEGER,
    "NUM_CUEN" VARCHAR(30),
    "CUEN_EXTR" CHAR(1),
    "NOM_ENT_EXT" VARCHAR(120),
    "TIP_CUE_EXT" VARCHAR(40),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "OTR_BANCO" VARCHAR(255),
    "OTR_CUEN" VARCHAR(255),
    "COD_PAIS_EXT" VARCHAR(10),
    "OTR_PAIS_EXT" VARCHAR(100),
    "CUENTAS_EXT" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_gn_terce_banco_cod_empr" ON public."GN_TERCE_BANCO" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_terce_banco_cod_terc" ON public."GN_TERCE_BANCO" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_terce_banco_act_esta" ON public."GN_TERCE_BANCO" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_TERCE_DOC" (
    "COD_DOC" INTEGER NOT NULL,
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_TERC" BIGINT NOT NULL,
    "TIP_DOC" VARCHAR(20) NOT NULL,
    "NOM_DOC" VARCHAR(120),
    "RUT_DOC" VARCHAR(500),
    "FEC_CARG" DATE,
    "FEC_VENC" DATE,
    "OBS_DOC" VARCHAR(300),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "NOM_ARCH" VARCHAR(260),
    "EXT_ARCH" VARCHAR(10),
    "TAM_ARCH" BIGINT,
    "HASH_ARCH" VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS "idx_gn_terce_doc_cod_empr" ON public."GN_TERCE_DOC" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_terce_doc_cod_terc" ON public."GN_TERCE_DOC" ("COD_TERC");
CREATE INDEX IF NOT EXISTS "idx_gn_terce_doc_act_esta" ON public."GN_TERCE_DOC" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."GN_USUAR" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_USUA" BIGINT NOT NULL,
    "COD_FUNCI" INTEGER DEFAULT 0,
    "NOM_USUA" CHAR(240) NOT NULL,
    "ABR_USUA" CHAR(8),
    "TIP_USUA" CHAR(1),
    "PAS_USUA" CHAR(16),
    "FEC_ACTI" TIMESTAMP,
    "FEC_EXPI" TIMESTAMP,
    "COD_GUSU" BIGINT,
    "VER_ACTU" CHAR(1),
    "CAM_PASS" CHAR(1),
    "FEC_ULCA" TIMESTAMP,
    "NRO_DICP" INTEGER,
    "ACT_INAC" CHAR(1),
    "FEC_ULEN" TIMESTAMP,
    "DIR_ELEC" CHAR(100),
    "NUM_CONE" SMALLINT,
    "DES_BLOQ" VARCHAR(50),
    "NUM_INTF" SMALLINT,
    "EVA_SESI" VARCHAR(40),
    "COD_PERF" SMALLINT,
    "USU_LARG" VARCHAR(100),
    "USU_TWEB" CHAR(1),
    "IMG_FIRM" BYTEA,
    "OBL_CPAS" CHAR(1),
    "SEL_PVTA" CHAR(1),
    "USU_TMOV" CHAR(1),
    "ID" CHAR(8),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "PAS_HASH" VARCHAR(255),
    "INT_FALL" SMALLINT DEFAULT 0,
    "IND_BLOQ" CHAR(1) DEFAULT 'N',
    "FEC_PRCA" TIMESTAMP,
    "TOK_RECO" VARCHAR(100),
    "FEC_TOKE" TIMESTAMP,
    "TOK_VERI" VARCHAR(255),
    "VER_EMAIL" CHAR(1) DEFAULT 'N',
    "FEC_VERI" TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "idx_gn_usuar_cod_empr" ON public."GN_USUAR" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_gn_usuar_act_esta" ON public."GN_USUAR" ("ACT_ESTA");

-- ============================================================
-- 3. TABLAS DE NÓMINA / NOVEDADES (NO_*)
-- ============================================================

CREATE TABLE IF NOT EXISTS public."NO_CONCE" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_CONC" INTEGER NOT NULL,
    "TIP_NATU" VARCHAR(15),
    "COD_INTE" CHAR(6),
    "NOM_CONC" VARCHAR(80) NOT NULL,
    "TIP_CONC" VARCHAR(10) DEFAULT 'DEVENGO',
    "TIP_MODA" VARCHAR(10) DEFAULT 'Normal',
    "TIP_APLIC" VARCHAR(15) DEFAULT 'Normal',
    "OPC_CANT" VARCHAR(12) DEFAULT 'Opcional',
    "OPC_VALU" VARCHAR(12) DEFAULT 'Obligatorio',
    "TAU_PRRG" BOOLEAN DEFAULT 0,
    "TAU_DIAG" BOOLEAN DEFAULT 0,
    "TC_CAMPO" VARCHAR(60),
    "IND_ACT" CHAR(10) DEFAULT (N'True'),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_no_conce_cod_empr" ON public."NO_CONCE" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_no_conce_ind_act" ON public."NO_CONCE" ("IND_ACT");
CREATE INDEX IF NOT EXISTS "idx_no_conce_act_esta" ON public."NO_CONCE" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."NO_NOVED" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_NOVED" INTEGER NOT NULL,
    "COD_FUNCI" INTEGER NOT NULL,
    "COD_CONC" INTEGER NOT NULL,
    "COD_PERIOD" INTEGER NOT NULL,
    "FEC_REGI" DATE NOT NULL DEFAULT (CONVERT([date],getdate())),
    "OBS_NOVED" VARCHAR(500),
    "IND_APLICADO" CHAR(1) NOT NULL DEFAULT 'N',
    "ACT_USUA" VARCHAR(50) NOT NULL DEFAULT (N'MineDax'),
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A',
    "FEC_INI" DATE,
    "FEC_FIN" DATE,
    "COD_CCOST" INTEGER
);
CREATE INDEX IF NOT EXISTS "idx_no_noved_cod_empr" ON public."NO_NOVED" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_no_noved_cod_period" ON public."NO_NOVED" ("COD_PERIOD");
CREATE INDEX IF NOT EXISTS "idx_no_noved_act_esta" ON public."NO_NOVED" ("ACT_ESTA");

CREATE TABLE IF NOT EXISTS public."NO_PERIOD" (
    "COD_EMPR" SMALLINT NOT NULL DEFAULT 1,
    "COD_PERIOD" INTEGER NOT NULL,
    "PER_ANO" SMALLINT NOT NULL,
    "PER_MES" SMALLINT NOT NULL,
    "PER_QNA" SMALLINT NOT NULL,
    "PER_FINI" DATE NOT NULL,
    "PER_FFIN" DATE NOT NULL,
    "PER_EST" CHAR(1) NOT NULL DEFAULT 'A',
    "PER_FCREO" TIMESTAMP NOT NULL DEFAULT (sysdatetime()),
    "ACT_USUA" CHAR(8) NOT NULL DEFAULT 'MineDax',
    "ACT_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "ACT_ESTA" CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS "idx_no_period_cod_empr" ON public."NO_PERIOD" ("COD_EMPR");
CREATE INDEX IF NOT EXISTS "idx_no_period_cod_period" ON public."NO_PERIOD" ("COD_PERIOD");
CREATE INDEX IF NOT EXISTS "idx_no_period_act_esta" ON public."NO_PERIOD" ("ACT_ESTA");

-- ============================================================
-- 4. ESQUEMA DE SEGURIDAD Y AUDITORÍA (sec.*)
-- ============================================================

-- AUDITORÍA INMUTABLE: Aplicar Row-Level Security (ver sección RLS al final)
CREATE TABLE IF NOT EXISTS sec."AUDIT_LOG" (
    "ID_LOG" BIGINT NOT NULL,
    "FECHA_HORA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "NOM_USUA" VARCHAR(50) NOT NULL,
    "ROL_USUA" VARCHAR(10),
    "IP_ORIGEN" VARCHAR(45),
    "TIPO_EVENTO" VARCHAR(20) NOT NULL,
    "NOM_TABLA" VARCHAR(128),
    "DETALLE" VARCHAR(500),
    "RESULTADO" CHAR(1) NOT NULL DEFAULT 'S'
);

CREATE TABLE IF NOT EXISTS sec."BLOQUEO" (
    "NOM_USUA" VARCHAR(50) NOT NULL,
    "INTENTOS" SMALLINT NOT NULL DEFAULT 0,
    "ULTIMO_INTENTO" TIMESTAMP,
    "BLOQUEADO_HASTA" TIMESTAMP
);

-- AUDITORÍA INMUTABLE: Aplicar Row-Level Security (ver sección RLS al final)
CREATE TABLE IF NOT EXISTS sec."HIST_NOMINA" (
    "ID_HIST" BIGINT NOT NULL,
    "FECHA_HORA" TIMESTAMP NOT NULL DEFAULT (sysdatetime()),
    "NOM_TABLA" VARCHAR(50) NOT NULL,
    "TIPO_OP" CHAR(1) NOT NULL,
    "ID_REG" VARCHAR(100),
    "NOM_USUA" VARCHAR(50) NOT NULL,
    "ROL_USUA" VARCHAR(10),
    "IP_ORIGEN" VARCHAR(45),
    "DATOS_ANT" TEXT,
    "DATOS_NUE" TEXT
);

-- TABLAS MAESTRAS: Candidato a ENUM PostgreSQL para columnas de estado/tipo
CREATE TABLE IF NOT EXISTS sec."MAE_ROL" (
    "ROL_USUA" VARCHAR(10) NOT NULL,
    "ROL_DESC" VARCHAR(100) NOT NULL,
    "ROL_NIVEL" SMALLINT NOT NULL DEFAULT 0,
    "IND_ACT" BOOLEAN NOT NULL DEFAULT 1,
    "FEC_CREA" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "MOD_USUA" VARCHAR(50) NOT NULL DEFAULT (suser_sname())
);
CREATE INDEX IF NOT EXISTS "idx_mae_rol_ind_act" ON sec."MAE_ROL" ("IND_ACT");

CREATE TABLE IF NOT EXISTS sec."PERMISOS" (
    "ID_PERM" INTEGER NOT NULL,
    "ROL_USUA" VARCHAR(10) NOT NULL,
    "NOM_TABLA" VARCHAR(128) NOT NULL,
    "PER_SELECT" BOOLEAN NOT NULL DEFAULT 0,
    "PER_INSERT" BOOLEAN NOT NULL DEFAULT 0,
    "PER_UPDATE" BOOLEAN NOT NULL DEFAULT 0,
    "PER_DELETE" BOOLEAN NOT NULL DEFAULT 0,
    "PER_EXPORT" BOOLEAN NOT NULL DEFAULT 0,
    "IND_ACT" BOOLEAN NOT NULL DEFAULT 1,
    "FEC_MOD" TIMESTAMP NOT NULL DEFAULT (getdate()),
    "MOD_USUA" VARCHAR(50) NOT NULL DEFAULT (suser_sname())
);
CREATE INDEX IF NOT EXISTS "idx_permisos_ind_act" ON sec."PERMISOS" ("IND_ACT");

-- ============================================================
-- 5. ROW-LEVEL SECURITY — tablas de auditoría inmutables
-- ============================================================

-- Hacer sec.AUDIT_LOG y sec.HIST_NOMINA de solo inserción (append-only)
-- Ningún usuario (ni superusuario de app) puede borrar ni modificar registros.

ALTER TABLE sec."AUDIT_LOG"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE sec."HIST_NOMINA" ENABLE ROW LEVEL SECURITY;

-- Solo INSERT permitido para el rol de aplicación
CREATE POLICY audit_insert_only ON sec."AUDIT_LOG"
    FOR INSERT WITH CHECK (true);
CREATE POLICY audit_no_delete ON sec."AUDIT_LOG"
    FOR DELETE USING (false);
CREATE POLICY audit_no_update ON sec."AUDIT_LOG"
    FOR UPDATE USING (false);

CREATE POLICY hist_insert_only ON sec."HIST_NOMINA"
    FOR INSERT WITH CHECK (true);
CREATE POLICY hist_no_delete ON sec."HIST_NOMINA"
    FOR DELETE USING (false);
CREATE POLICY hist_no_update ON sec."HIST_NOMINA"
    FOR UPDATE USING (false);

-- ============================================================
-- 6. FOREIGN KEYS — agregar DESPUÉS de validar datos migrados
-- ============================================================
-- Ejemplo:
-- ALTER TABLE public."GN_FUNCI"
--   ADD CONSTRAINT fk_funci_terc FOREIGN KEY ("COD_TERC")
--   REFERENCES public."GN_TERCE" ("COD_TERC");
--
-- Ejecutar VALIDATE CONSTRAINT después de cada FK agregada.

-- ============================================================
-- 7. ENUMs RECOMENDADOS para tablas maestras
-- ============================================================

-- PostgreSQL ENUM vs tabla maestra:
--   ENUM: mejor rendimiento en JOINs frecuentes, valores fijos conocidos.
--   Tabla maestra: más flexible, permite agregar valores sin ALTER TYPE.
--
-- Para MineDax se recomienda ENUM para estados simples de 1 char:
CREATE TYPE tipo_estado AS ENUM ('A', 'I', 'P', 'C', 'R');
CREATE TYPE tipo_resultado AS ENUM ('S', 'F', 'W');
CREATE TYPE tipo_operacion AS ENUM ('I', 'U', 'D');
--
-- Uso: en vez de CHAR(1) NOT NULL DEFAULT 'A',
--      usar tipo_estado NOT NULL DEFAULT 'A'
-- Las columnas ACT_ESTA en todas las tablas son candidatos directos.
